# Generated by Django 6.0.7 on 2026-07-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse_livraison', models.TextField(verbose_name='Adresse de livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('items', models.JSONField(verbose_name='Articles commandés')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('statut', models.CharField(choices=[('En_attente', 'En attente'), ('Confirmee', 'Confirmée'), ('En_preparation', 'En préparation'), ('Livree', 'Livrée'), ('Annulee', 'Annulée')], default='En_attente', max_length=20, verbose_name='Statut')),
                ('whatsapp_sent', models.BooleanField(default=False, verbose_name='WhatsApp envoyé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
    ]
